export const SET_WIDTH = 'data/set_width'
export const SET_DATA = 'data/set_data'
export const SET_LOADED = 'data/set_loaded'
export const SET_FAVOURITES = 'data/set_favourites'
export const SET_RECENT = 'data/set_recent'
export const SET_RECOMMENDED = 'data/set_recommended'

export const SET_FILTERS_VISIBILITY = 'filters/set_filters_visibility'
export const TOGGLE_PROVIDER = 'filters/toggle_provider'
export const SET_CATEGORY = 'filters/set_category'
